staging:
  user-workflow:
    workflow-name: 'private-hire-jobs-staging-simulation'
  workflow-artifacts:
    workflow-path: './main.ts'
    config-path: './config.staging.json'
    secrets-path: './secrets.yaml'
