'use client';

import {
  createContext,
  Fragment,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ReactNode,
} from 'react';
import {
  QueryClient,
  QueryClientProvider,
  useQueryClient,
} from '@tanstack/react-query';
import {
  createConfig,
  http,
  WagmiProvider,
  useAccount,
  useConfig,
} from 'wagmi';
import { getAccount, getWalletClient, watchAccount } from 'wagmi/actions';
import {
  ConnectButton,
  connectorsForWallets,
  createAuthenticationAdapter,
  darkTheme,
  RainbowKitAuthenticationProvider,
  RainbowKitProvider,
} from '@rainbow-me/rainbowkit';
import { injectedWallet } from '@rainbow-me/rainbowkit/wallets';
import { parseSiweMessage } from 'viem/siwe';
import type { Address, Hex } from 'viem';
import { arcChain } from '@private-hire/chain';

export async function api<T>(url: string, body?: unknown): Promise<T> {
  const response = await fetch(url, {
    method: body === undefined ? 'GET' : 'POST',
    headers: body === undefined ? {} : { 'Content-Type': 'application/json' },
    body: body === undefined ? undefined : JSON.stringify(body),
    cache: 'no-store',
  });
  const result = await response.json();
  if (!response.ok)
    throw new Error(result.error ?? 'Request failed. Try again.');

  return result;
}

function makeConfig() {
  return createConfig({
    chains: [arcChain],
    // Browser extensions only: no WalletConnect relay or project credential is needed.
    connectors: connectorsForWallets(
      [{ groupName: 'Browser wallets', wallets: [injectedWallet] }],
      {
        appName: 'Confidential Agent Jobs',
        projectId: '',
      },
    ),
    transports: { [arcChain.id]: http() },
    ssr: true,
  });
}

type Transaction = { from: string; to: string; data: string; chainId: number };
type WalletState = {
  account: string | null;
  send: (tx: Transaction) => Promise<Hex>;
};
const Context = createContext<WalletState>({
  account: null,
  send: async () => {
    throw new Error('Sign in first.');
  },
});
export const useWallet = () => useContext(Context);

export function WalletProvider({ children }: { children: ReactNode }) {
  const [config] = useState(makeConfig);
  const [queryClient] = useState(
    () =>
      new QueryClient({
        defaultOptions: { queries: { retry: 1 }, mutations: { retry: false } },
      }),
  );

  return (
    <WagmiProvider config={config}>
      <QueryClientProvider client={queryClient}>
        <SessionProvider>{children}</SessionProvider>
      </QueryClientProvider>
    </WagmiProvider>
  );
}

function SessionProvider({ children }: { children: ReactNode }) {
  const config = useConfig();
  const queryClient = useQueryClient();
  const wallet = useAccount();
  const [session, setSession] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [notice, setNotice] = useState('');
  const epoch = useRef(0);
  const queue = useRef<Promise<unknown>>(Promise.resolve());
  const messages = useRef(new Map<string, number>());
  const account =
    wallet.isConnected &&
    wallet.chainId === arcChain.id &&
    session === wallet.address?.toLowerCase()
      ? session
      : null;

  const auth = useMemo(() => {
    function enqueue<T>(work: () => Promise<T>) {
      const operation = queue.current.catch(() => {}).then(work);
      queue.current = operation;

      return operation;
    }

    async function signOut() {
      epoch.current++;
      messages.current.clear();
      setSession(null);
      await enqueue(() => api('/api/auth/logout', {}));
    }

    const adapter = createAuthenticationAdapter<string>({
      // RainbowKit needs a readiness token; the actual SIWE nonce is generated by our server in createMessage.
      getNonce: async () => 'server-generated',
      createMessage: async ({ address, chainId }) => {
        setNotice('');
        if (chainId !== arcChain.id) throw new Error('Switch to Arc Testnet.');
        const version = epoch.current;
        const challenge = await api<{ nonce: string; message: string }>(
          '/api/auth/nonce',
          { wallet: address },
        );
        if (
          version !== epoch.current ||
          getAccount(config).address?.toLowerCase() !== address.toLowerCase()
        )
          throw new Error('Wallet changed.');
        messages.current.set(challenge.message, version);

        return challenge.message;
      },
      verify: async ({ message, signature }) =>
        enqueue(async () => {
          const version = messages.current.get(message);
          messages.current.delete(message);
          const parsed = parseSiweMessage(message);
          const current = () => {
            const connected = getAccount(config);
            return (
              version === epoch.current &&
              connected.isConnected &&
              connected.chainId === arcChain.id &&
              connected.address?.toLowerCase() === parsed.address?.toLowerCase()
            );
          };
          if (version === undefined || !current()) return false;
          const result = await api<{ wallet: string }>('/api/auth/verify', {
            nonce: parsed.nonce,
            signature,
          });
          if (!current() || result.wallet !== parsed.address?.toLowerCase()) {
            await api('/api/auth/logout', {});
            return false;
          }
          setSession(result.wallet);
          setNotice('');

          return true;
        }),
      signOut: async () => {
        try {
          await signOut();
        } catch {
          setNotice('Session could not be cleared. Please retry.');
        }
      },
    });

    return { adapter, signOut };
  }, [config]);

  useEffect(() => {
    let disposed = false;
    // Subscribe to wagmi's canonical account state, including events during a pending signature.
    const unwatch = watchAccount(config, {
      onChange(next, previous) {
        if (
          previous.address &&
          (next.address !== previous.address ||
            next.chainId !== previous.chainId ||
            next.connector?.uid !== previous.connector?.uid)
        ) {
          void auth
            .signOut()
            .catch(() =>
              setNotice('Session could not be cleared. Please retry.'),
            );
        }
      },
    });
    const version = epoch.current;
    void api<{ wallet: string }>('/api/auth/session')
      .then((result) => {
        if (!disposed && version === epoch.current) setSession(result.wallet);
      })
      .catch(() => {})
      .finally(() => {
        if (!disposed) setLoading(false);
      });

    return () => {
      disposed = true;
      unwatch();
    };
  }, [config, auth]);

  useEffect(
    () =>
      queryClient.getMutationCache().subscribe((event) => {
        if (event.type !== 'updated' || event.action.type !== 'error') return;
        let error: unknown = event.mutation.state.error;
        const seen = new Set<unknown>();
        while (error && typeof error === 'object' && !seen.has(error)) {
          seen.add(error);
          const item = error as { code?: number; cause?: unknown };
          if (item.code === 4001) {
            setNotice('Request canceled in your wallet. You can try again.');
            return;
          }
          if (item.code === -32002) {
            setNotice(
              'A request is pending in your wallet. Open the extension to finish it.',
            );
            return;
          }
          error = item.cause;
        }
      }),
    [queryClient],
  );

  useEffect(() => {
    if (!notice) return;
    const timeout = window.setTimeout(() => setNotice(''), 8000);

    return () => window.clearTimeout(timeout);
  }, [notice]);

  async function send(tx: Transaction): Promise<Hex> {
    if (
      !account ||
      tx.from.toLowerCase() !== account ||
      tx.chainId !== arcChain.id
    )
      throw new Error('Sign in with the wallet assigned to this action.');
    const version = epoch.current;
    const client = await getWalletClient(config);
    const [addresses, chainId] = await Promise.all([
      client.getAddresses(),
      client.getChainId(),
    ]);
    if (
      version !== epoch.current ||
      addresses[0]?.toLowerCase() !== account ||
      chainId !== arcChain.id
    )
      throw new Error('Wallet or network changed. Sign in again.');

    return client.sendTransaction({
      account: addresses[0] as Address,
      chain: arcChain,
      to: tx.to as Address,
      data: tx.data as Hex,
      value: 0n,
    });
  }

  return (
    <RainbowKitAuthenticationProvider
      adapter={auth.adapter}
      status={
        loading ? 'loading' : account ? 'authenticated' : 'unauthenticated'
      }
    >
      <RainbowKitProvider
        locale="en-US"
        modalSize="compact"
        theme={darkTheme({
          accentColor: '#bce6cc',
          accentColorForeground: '#152820',
          borderRadius: 'medium',
          fontStack: 'system',
        })}
        appInfo={{ appName: 'Confidential Agent Jobs' }}
      >
        <Context.Provider value={{ account, send }}>
          <Fragment key={account ?? 'signed-out'}>{children}</Fragment>
          {notice && (
            <div className="wallet-notice" role="alert">
              {notice}
            </div>
          )}
        </Context.Provider>
      </RainbowKitProvider>
    </RainbowKitAuthenticationProvider>
  );
}

export function WalletControl() {
  return (
    <div className="wallet-control">
      <ConnectButton
        label="Connect wallet"
        showBalance={false}
        chainStatus="icon"
        accountStatus="address"
      />
    </div>
  );
}
