deployed-probe:
  user-workflow:
    workflow-name: 'private-hire-tee-zone-b-probe'
    deployment-registry: 'private'
  workflow-artifacts:
    workflow-path: './main.ts'
    config-path: './config.json'
    secrets-path: './secrets.yaml'
